spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: root
    password: bondiILIAS321
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
jwt:
  publicKey: classpath:app.pub
  privateKey: classpath:app.key


server:
  error:
    include-message: always
